    tcp dport ssh accept comment "allow sshd"
    tcp dport 4747 accept comment "droidcam"
	ip saddr 10.10.42.0/27 tcp dport 137 ct state new accept comment "Accept SMB/CIFS from local network"
	ip saddr 10.10.42.0/27 tcp dport 138 ct state new accept comment "Accept SMB/CIFS from local network"
	ip saddr 10.10.42.0/27 tcp dport 139 ct state new accept comment "Accept SMB/CIFS from local network"
	ip saddr 10.10.42.0/27 tcp dport 445 ct state new accept comment "Accept SMB/CIFS from local network"
