#!/bin/bash
if [[ "${NFTD_DIR:-}" == "" ]]; then
  if [[ -f ./nft-deploy.py && -f ./nft-failsafe.py ]]; then
    ./.venv/bin/python3 ./nft-deploy.py "$@"
  else
    exit 1
  fi
else
cd "$NFTD_DIR" || exit 1
sudo ./.venv/bin/python3 ./nft-deploy.py "$@"
fi
exit 0